apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-store
  labels:
    app: event-store
spec:
  replicas: {{ .Values.eventStore.replicas }}
  selector:
    matchLabels:
      app: event-store
  template:
    metadata:
      labels:
        app: event-store
    spec:
      containers:
        - name: event-store
          image: {{ .Values.eventStore.image }}
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: tradepulse-config
          env:
            - name: KAFKA__CONSUMERGROUP
              value: "eventstore-group"
            - name: KAFKA__TOPICS__ORDERS
              value: "trade.orders"
            - name: KAFKA__TOPICS__EXECUTIONS
              value: "trade.executions"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"